manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: pmd-coutinho
      url-base: https://github.com/pmd-coutinho
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-oled-adapter
      remote: pmd-coutinho
      revision: main
  self:
    path: config
